{{- if .Values.rbac.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "logging-operator.fullname" . }}-user
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - logging-extensions.banzaicloud.io
  resources:
  - eventtailers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logging-extensions.banzaicloud.io
  resources:
  - eventtailers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - logging.banzaicloud.io
  resources:
  - flows
  - outputs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logging.banzaicloud.io
  resources:
  - flows/status
  - outputs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - logging.banzaicloud.io
  resources:
  - syslogngflows
  - syslogngoutputs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logging.banzaicloud.io
  resources:
  - syslogngflows/status
  - syslogngoutputs/status
  verbs:
  - get
  - patch
  - update
{{- end }}
